final Map<String, String> en = {
  // "lbl2": "\$",
  // "lbl_0": "0",
  // "lbl_1": "1",
  // "lbl_2": "2",
  // "lbl6": "***",
  // "lbl3": "\$\$",
  // "lbl_05": "05",
  // "lbl_20": "20",
  // "lbl_ok": "Ok",
  // "lbl_or": "Or",
  // "lbl_10": "10”",
  // "lbl_14": "14”",
  // "lbl_16": "16”",
  // "lbl4": "\$\$\$",
  // "lbl_25": "\$25",
  // "lbl_29k": "29K",
  // "lbl_30": "\$30",
  // "lbl_32": "\$32",
  // "lbl_345": "345",
  // "lbl_35": "\$35",
  // "lbl_40": "\$40",
  // "lbl_436": "436",
  // "lbl_45": "\$45",
  // "lbl_4_3": "4.3",
  // "lbl_4_7": "4.7",
  // "lbl_4_9": "4.9",
  // "lbl_50": "\$50",
  // "lbl_60": "\$60",
  // "lbl_64": "\$64",
  // "lbl_70": "\$70",
  // "lbl_75": "\$75",
  // "lbl_94": "\$94",
  // "lbl_96": "\$96",
  // "lbl_add": "Add",
  // "lbl_all": "All",
  // "lbl_bio": "Bio",
  // "lbl_cvc": "cvc",
  // "lbl_142": "14'’",
  // "lbl_4_02": "4.0",
  // "lbl_01pm": "01pm",
  // "lbl_02pm": "02pm",
  // "lbl_03pm": "03pm",
  // "lbl_04pm": "04pm",
  // "lbl_10am": "10am",
  // "lbl_11am": "11am",
  // "lbl_12pm": "12pm",
  // "lbl_500": "\$500",
  // "lbl_cart": "Cart",
  // "lbl_cash": "Cash",
  // "lbl_code": "Code",
  // "lbl_done": "Done",
  // "lbl_edit": "Edit",
  // "lbl_faqs": "FAQs",
  // "lbl_food": "Food",
  // "lbl_free": "Free",
  // "lbl_home": "Home",
  // "lbl_name": "Name",
  "lbl_next": "Next",
  // "lbl_rate": "Rate",
  // "lbl_salt": "Salt",
  // "lbl_save": "Save",
  "lbl_skip": "Skip",
  // "lbl_visa": "Visa",
  // "lbl_work": "Work",
  // "lbl": "**********",
  // "lbl_edit2": "EDIT",
  // "lbl_size": "Size:",
  // "lbl_19_37": "19:37",
  // "lbl_34567": "34567",
  // "lbl_apple": "Apple",
  // "lbl_basic": "Basic",
  // "lbl_daily": "Daily",
  // "lbl_drink": "Drink",
  // "lbl_email": "Email",
  // "lbl_fruit": "Fruit",
  // "lbl_lunch": "Lunch",
  // "lbl_offer": "Offer",
  // "lbl_onion": "onion",
  // "lbl_other": "Other",
  // "lbl_pizza": "Pizza",
  // "lbl_price": "PRice",
  // "lbl_reset": "Reset",
  // "lbl_10_20": "\$10.20",
  // "lbl_20_min": "20 min",
  // "lbl_2_241": "\$2,241",
  // "lbl_30_min": "30 min",
  // "lbl_35_25": "\$35.25",
  // "lbl_40_15": "\$40.15",
  // "lbl_burger": "Burger",
  // "lbl_cancel": "Cancel",
  // "lbl_dinner": "Dinner",
  // "lbl_filter": "Filter",
  // "lbl_garlic": "Garlic",
  // "lbl_ginger": "Ginger",
  // "lbl_got_it": "Got it",
  // "lbl_log_in": "Log In",
  // "lbl_offers": "Offers",
  // "lbl_orange": "Orange",
  // "lbl_paypal": "PayPal",
  // "lbl_rating": "Rating",
  // "lbl_search": "Search",
  // "lbl_street": "street",
  // "lbl_total": "Total: ",
  // "lbl_total2": "Total:",
  // "lbl_verify": "Verify",
  // "lbl_walnut": "Walnut",
  // "lbl5": "*************",
  // "lbl_162432": "#162432",
  // "lbl_240112": "#240112",
  // "lbl_242432": "#242432",
  // "lbl_onion2": "onion\n",
  // "lbl_500_00": "\$500.00",
  // "lbl_8_10_pm": "8:10 pm",
  // "lbl_8_11_pm": "8:11 pm",
  // "lbl_8_12_pm": "8:12 pm",
  // "lbl_add_new": "Add New",
  // "lbl_address": "Address",
  // "lbl_alergy": "(Alergy)",
  // "lbl_avocado": "Avocado",
  // "lbl_chicken": "Chicken",
  // "lbl_courier": "Courier",
  // "lbl_details": "Details",
  // "lbl_history": "History",
  // "lbl_hot_dog": "Hot Dog",
  // "lbl_log_out": "Log Out",
  // "lbl_mm_yyyy": "mm/yyyy",
  // "lbl_ongoing": "Ongoing",
  // "lbl_pappers": "Pappers",
  // "lbl_payment": "Payment",
  // "lbl_pricing": "Pricing",
  // "lbl_profile": "Profile",
  // "lbl_reviews": "Reviews",
  // "lbl_sanwich": "Sanwich",
  // "lbl_see_all": "See All",
  // "lbl_sign_up": "Sign Up",
  // "lbl_pick_up": " Pick UP",
  // "lbl_pick_up2": "Pick up",
  // "lbl_pick_up3": "Pick Up",
  // "lbl_01_items": "01 Items",
  // "lbl_02_items": "02 Items",
  // "lbl_03_items": "03 Items",
  // "lbl_add_card": "Add Card",
  // "lbl_broccoli": "Broccoli",
  // "lbl_canceled": "Canceled",
  // "lbl_delivery": "Delivery",
  // "lbl_john_doe": "John doe",
  // "lbl_label_as": "Label as",
  // "lbl_location": "Location",
  // "lbl_mcdonald": "McDonald",
  // "lbl_pappers2": "Pappers�",
  // "lbl_password": "Password",
  // "lbl_re_order": "Re-Order",
  // "lbl_sandwich": "Sandwich",
  // "lbl_settings": "Settings",
  // "lbl_withdraw": "Withdraw",
  // "lbl_id_15253": "ID: 15253",
  // "lbl_id_21200": "ID: 21200",
  // "lbl_id_32053": "ID: 32053",
  // "lbl_id_53241": "ID: 53241",
  // "lbl_robert_f": "Robert F.",
  // "lbl_starting": "Starting ",
  // "lbl_10_15_min": "10-15 min",
  // "lbl_123456789": "123456789",
  // "lbl_1243cd2": "#1243CD2 \n",
  // "lbl_2x_burger": "2x Burger",
  // "lbl_addresses": "Addresses",
  // "lbl_blueberry": "Blueberry",
  // "lbl_breakdown": "breakdown",
  // "lbl_completed": "Completed",
  // "lbl_favourite": "Favourite",
  // "lbl_full_name": "Full Name",
  // "lbl_item_name": "item name",
  // "lbl_my_orders": "My Orders",
  // "lbl_pizza_hut": "Pizza Hut",
  // "lbl_post_code": "Post code",
  // "lbl_send_code": "Send Code",
  // "lbl_starbucks": "Starbucks",
  // "lbl_breakfast": "#Breakfast",
  // "lbl_breakfast2": "Breakfast",
  // "lbl_10_review": "(10 Review)",
  // "lbl_20_12_2020": "20/12/2020",
  // "lbl_20_min_ago": "20 min ago",
  // "lbl_appartment": "Appartment",
  // "lbl_burger_10": "Burger (10)",
  // "lbl_deliver_to": "Deliver to",
  // "lbl_edit_items": "EDIT Items",
  // "lbl_hey_halal": "Hey Halal, ",
  // "lbl_ingridents": "ingridents",
  // "lbl_mastercard": "Mastercard",
  // "lbl_meat_pizza": "Meat Pizza",
  // "lbl_my_address": "My Address",
  // "lbl_my_profile": "My Profile",
  // "lbl_robert_fox": "Robert Fox",
  // "lbl_10_reviews": "(10 Reviews)",
  // "lbl_4x_sanwitch": "4x Sanwitch",
  // "lbl_add_to_cart": "Add to cart",
  // "lbl_card_number": "Card number",
  // "lbl_cody_fisher": "Cody Fisher",
  // "lbl_description": "Description",
  // "lbl_expire_date": "expire date",
  // "lbl_get_started": "Get Started",
  // "lbl_hason_nagar": "hason nagar",
  // "lbl_messages_3": "Messages (3)",
  // "lbl_pabel_vuiya": "Pabel Vuiya",
  // "lbl_place_order": "Place ORder",
  // "lbl_rose_garden": "Rose garden",
  // "lbl_salim_smith": "Salim Smith",
  // "lbl_see_details": "See Details",
  // "lbl_track_order": "Track Order",
  // "lbl_master_card2": "Master Card",
  // "lbl_remember_me": "Remember me ",
  // "lbl_rose_garden2": "Rose Garden",
  // "lbl_thanks_dude": "Thanks dude.",
  // "lbl_408_841_0926": "408-841-0926",
  // "lbl_deliver_time": "Deliver Time",
  // "lbl_edit_profile": "Edit Profile",
  // "lbl_eleanor_pena": "Eleanor Pena",
  // "lbl_food_details": "Food Details",
  // "lbl_my_food_list": "My Food List",
  // "lbl_pay_confirm": "Pay & Confirm",
  // "lbl_phone_number": "Phone Number",
  // "lbl_royal_bengol": "Royal Bengol",
  // "lbl_royal_parvej": "Royal Parvej",
  // "lbl_save_changes": "Save Changes",
  // "lbl_spicy_burger": "Spicy burger",
  // "lbl_tanbir_ahmed": "Tanbir Ahmed",
  // "lbl_user_reviews": "User Reviews",
  // "lbl_verification": "Verification",
  // "msg_network_err": "Network Error",
  // "lbl_29_jan_12_30": "29 Jan, 12:30",
  // "lbl_30_jan_12_30": "30 Jan, 12:30",
  // "lbl_hurry_offers": "Hurry Offers!",
  // "lbl_hurry_up_man": "Hurry Up, Man",
  // "lbl_add_new_items": "Add New Items",
  // "lbl_burger_bistro": "Burger Bistro",
  // "lbl_cafecafachino": "Cafecafachino",
  // "lbl_chicken_bhuna": "Chicken Bhuna",
  // "lbl_notifications": "Notifications",
  // "lbl_order_request": "Order Request",
  // "lbl_personal_info": "Personal Info",
  // "lbl_ralph_edwards": "Ralph Edwards",
  // "lbl_save_location": "Save location",
  // "lbl_total_revenue": "Total Revenue",
  // "lbl_vishal_khadok": "Vishal Khadok",
  // "lbl_buffalo_pizza": "Buffalo Pizza.",
  // "lbl_onion_alergy": "onion\n(Alergy)",
  // "lbl_smokin_burger": "Smokin' Burger",
  // "msg_connecting": "Connecting.......",
  // "lbl_all_categories": "All Categories",
  // "lbl_european_pizza": "european Pizza",
  // "lbl_kentucky_39495": "Kentucky 39495",
  // "lbl_payment_method": "Payment Method",
  // "lbl_running_orders": "Running Orders",
  // "lbl_total_03_items": "Total 03 items",
  // "msg_2134": "2134   _ _ _ _   _ _ _ _",
  // "msg_how_is_going": "How is going...?",
  // "lbl_are_you_coming": "Are you coming?",
  // "lbl_good_afternoon": "Good Afternoon!",
  // "lbl_rockin_burgers": "Rockin' Burgers",
  // "lbl_sounds_awesome": "Sounds awesome!",
  // "lbl_access_location": "Access LOCATION",
  // "lbl_add_new_address": "Add new address",
  // "lbl_buffalo_burgers": "Buffalo Burgers",
  // "lbl_burger_ferguson": "Burger Ferguson",
  // "lbl_forgot_password": "Forgot Password",
  // "lbl_open_resturants": "Open Resturants",
  // "lbl_popular_burgers": "Popular Burgers",
  // "lbl_recent_keywords": "Recent Keywords",
  // "lbl_resend_in_50sec": "Resend in.50sec",
  // "lbl_restaurant_view": "Restaurant View",
  // "lbl_see_all_reviews": "See All Reviews",
  // "msg_pappers_alergy": "Pappers�(Alergy)",
  // "msg_congratulations": "Congratulations!",
  // "lbl_resend_in_50sec2": " Resend in.50sec",
  // "msg_awesome_and_nice": "Awesome and Nice",
  // "msg_bullseye_burgers": "Bullseye Burgers",
  // "msg_card_holder_name": "card holder name",
  // "msg_delivery_address": "Delivery Address",
  // "msg_halal_lab_office": "Halal Lab office",
  // "msg_i_love_fast_food": "I love fast food",
  // "msg_kabab_restaurant": "Kabab restaurant",
  // "msg_number_of_orders": "Number of Orders",
  // "msg_open_restaurants": "Open Restaurants",
  // "msg_pansi_restaurant": "Pansi Restaurant",
  // "msg_re_type_password": "Re-Type Password",
  // "msg_spicy_restaurant": "Spicy restaurant",
  // "msg_total_20_reviews": "Total 20 Reviews",
  // "msg_write_somethings": "Write somethings",
  // "msg_20_running_orders": "20 Running Orders",
  // "msg_add_make_payment": "Add & Make Payment",
  // "msg_agreed_to_cancel": "agreed to \ncancel",
  // "msg_available_balance": "Available Balance",
  // "msg_example_gmail_com": "example@gmail.com",
  // "msg_hello_halallab_co": "hello@halallab.co",
  // "msg_kaji_firm_kitchen": "Kaji Firm Kitchen",
  // "msg_popular_fast_food": "Popular Fast food",
  "msg_onboarding_title_1": "All your favorites",
  // "msg_cafenio_restaurant": "Cafenio Restaurant",
  // "msg_cameron_williamson": "Cameron Williamson",
  // "msg_filter_your_search": "Filter your search",
  // "msg_mazalichiken_halim": "Mazalichiken Halim",
  // "msg_upload_photo_video": "Upload photo/video",
  // "msg_uttora_coffe_house": "Uttora Coffe House",
  // "msg_vegetarian_poutine": "Vegetarian Poutine",
  // "msg_withdrawal_history": "Withdrawal History",
  // "msg_placed_a_new_order": "Placed a\nnew order",
  // "msg_cafenio_coffee_club": "Cafenio Coffee Club",
  // "msg_tasty_treat_gallery": "Tasty treat Gallery",
  // "msg_turkey_bacon_strips": "Turkey Bacon Strips",
  // "msg_uttora_coffee_house": "Uttora Coffee House",
  // "msg_withdraw_successful": "Withdraw Successful",
  // "msg_hey_where_are_you": "Hey Where are you now?",
  // "msg_order_arriving_soon": "Order arriving soon!",
  // "msg_placed_a_new_order2": " Placed a\nnew order",
  // "msg_free_delivery_offers": "Free delivery offers",
  // "msg_hey_halal_good": "Hey Halal, Good Afternoon!",
  // "msg_no_master_card_added": "No master card added",
  // "msg_estimated_delivery": "Estimated delivery time",
  // "msg_i_m_coming_just": "I’m Coming , just wait ...",
  // "msg_order_from_choosen": "Order from choosen chef",
  // "msg_something_went_wrong": "Something Went Wrong!",
  // "msg_chicken_thai_biriyani": "Chicken Thai Biriyani",
  // "msg_move_to_edit_location": "Move to edit location",
  // "msg_populer_items_this": "Populer Items This Weeks",
  // "msg_suggested_restaurants": "Suggested Restaurants",
  // "msg_don_t_have_an_account": "Don’t have an account?",
  // "msg_left_a_5_star_review": "left a 5 star \nreview ",
  // "msg_orderd_at_06_sept": "Orderd at 06 Sept, 10:00pm",
  // "msg_2118_thornridge": "2118 Thornridge Cir. Syracuse",
  // "msg_great_food_and_service": "Great Food and Service",
  // "msg_pizza_calzone_european": "pizza calzone european",
  // "msg_rose_garden_restaurant": "rose garden restaurant",
  // "msg_burger_chiken": "Burger - Chiken - Riche - Wings ",
  // "msg_please_sign_up_to": "Please sign up to get started",
  // "msg_american_spicy_burger": "American Spicy Burger Shop",
  // "msg_hay_congratulation": "Hay, Congratulation for order",
  // "msg_use_the_cupon_get": "Use the cupon get 25% discount",
  // "msg_your_order_has_been": "Your order has been received",
  // "msg_online_payment_available": "Online payment available",
  // "msg_ok_just_hurry_up": "Ok, Just hurry up little bit...😊",
  // "msg_pabel_vuiya_placed": "Pabel Vuiya Placed a\nnew order",
  // "msg_royal_bengol_agreed": "Royal Bengol agreed to \ncancel",
  // "msg_salim_smith_left": "Salim Smith left a 5 star \nreview ",
  // "msg_search_dishes_restaurants": "Search dishes, restaurants",
  // "msg_tanbir_ahmed_placed": "Tanbir Ahmed Placed a\nnew order",
  // "msg_this_food_so_tasty3": "This Food so tasty & delicious. ",
  // "msg_we_have_sent_a_code": "We have sent a code to your email",
  // "msg_3235_royal_ln_mesa": "3235 Royal Ln. mesa, new jersy 34567",
  // "msg_the_restaurant_is": "The restaurant is preparing your food",
  // "msg_2464_royal_ln_mesa": "2464 Royal Ln. Mesa, New Jersey 45463",
  // "msg_1243cd2_use_the": "#1243CD2 \nUse the cupon get 25% discount",
  // "msg_please_sign_in_to": "Please sign in to your existing account",
  // "msg_thanks_for_the_awesome": "Thanks for the awesome food man...!",
  // "msg_your_order_has_been2": "Your order has been picked up for delivery",
  // "msg_3891_ranchview_dr": "3891 Ranchview Dr. Richardson, California 62639",
  // "msg_you_successfully":
  //     "You successfully maked a payment,\nenjoy our service!",
  // "msg_you_can_add_a_mastercard":
  //     "You can add a mastercard and save it for later",
  'msg_dont_worry_you_can_change_it_later':
      'Don\'t worry, you can change it later',
  // "msg_dfood_will_access":
  //     "DFOOD WILL ACCESS YOUR LOCATION ONLY WHILE USING THE APP",
  'msg_please_select_your_preferred_language':
      'Please select your preferred language',
  // "msg_prosciutto_e_funghi":
  //     "Prosciutto e funghi is a pizza variety that is topped with tomato sauce.",
  // "msg_this_food_so_tasty2":
  //     "This Food so tasty & delicious. Breakfast \nso fast Delivered in my place. ",
  // "msg_get_all_your_loved":
  //     "Get all your loved foods in one once place,\nyou just place the orer we do the rest",
  // "msg_lorem_ipsum_dolor":
  //     "Lorem ipsum dolor sit amet, consectetur adips cing elit. Bibendum in vel, mattis et amet dui mauris turpis.",
  // "msg_lorem_ipsum_dolor2":
  //     "Lorem ipsum dolor sit amet, consetdur Maton adipiscing elit. Bibendum in vel, mattis et amet dui mauris turpis.",
  // "msg_maecenas_sed_diam":
  //     "Maecenas sed diam eget risus varius blandit sit amet non magna. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.",
  // "msg_this_food_so_tasty":
  //     "This Food so tasty & delicious. Breakfast \nso fast Delivered in my place. Chef is very \nfriendly. I’m really like chef for Home Food \nOrder. Thanks. ",
};
