// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS6iBvXRO8vCTfpZ91qAJfnVjF5KF-H_A',
    appId: '1:489020360954:android:14bd415ca286ce253ae143',
    messagingSenderId: '489020360954',
    projectId: 'maxfit-ea591',
    storageBucket: 'maxfit-ea591.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAOsENEPtG_bDiCAjfkUH6Q8gwy8cUD74',
    appId: '1:489020360954:ios:a2bb55b61f401d943ae143',
    messagingSenderId: '489020360954',
    projectId: 'maxfit-ea591',
    storageBucket: 'maxfit-ea591.firebasestorage.app',
    androidClientId: '489020360954-coo6utro3rbnjv9akuacif95a5ehhc5j.apps.googleusercontent.com',
    iosClientId: '489020360954-4e083olvljjhna13kdcsfv960hspvp72.apps.googleusercontent.com',
    iosBundleId: 'com.codinggero.maxfit',
  );
}
